DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS USER_TOKEN;

DROP SEQUENCE IF EXISTS USER_SEQ;
DROP SEQUENCE IF EXISTS TOKEN_SEQ;

CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TOKEN_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE USER (
    id int PRIMARY KEY NOT NULL,
    username varchar(100) NOT NULL,
    password varchar(100) NOT NULL,
    description varchar(225),
    CONSTRAINT UC_Username UNIQUE (username)
);

CREATE TABLE USER_TOKEN (
    id int PRIMARY KEY NOT NULL,
    user_id int NOT NULL,
    uuid varchar(225) NOT NULL,
    active boolean DEFAULT FALSE,
    CONSTRAINT FK_USER_USERTOKEN FOREIGN KEY(user_id) REFERENCES USER(id)
)

